# ============================================================================
# Push ThinkSpark to a NEW Hugging Face model repo, with a model card.
# Copy-paste this whole file into a Kaggle cell (or run: python scripts/push_to_hf.py)
#
# Token: set HF_TOKEN in the environment, or add HF_TOKEN in Kaggle Secrets.
# Never commit a real token.
# ============================================================================
import json
import os
from pathlib import Path

import torch
from huggingface_hub import HfApi


def _hf_token() -> str:
    tok = (os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_HUB_TOKEN") or "").strip()
    if not tok:
        try:
            from kaggle_secrets import UserSecretsClient
            tok = UserSecretsClient().get_secret("HF_TOKEN").strip()
        except Exception:
            pass
    if not tok or not tok.startswith("hf_"):
        raise SystemExit(
            "Missing HF_TOKEN. Export HF_TOKEN=hf_... or add Kaggle Secret HF_TOKEN."
        )
    return tok


HF_TOKEN = _hf_token()
HF_USER = "anuj-inavlabs"

CKPT = Path("artifacts/thinkspark/best")             # trained checkpoint dir
FILLER = Path("data/vocab/filler_dictionary.json")

# ---- 1. param count -> fancy name -----------------------------------------
sd = torch.load(CKPT / "model.pt", map_location="cpu")
n_params = sum(v.numel() for v in sd.values() if hasattr(v, "numel"))
tag = f"{n_params/1e6:.1f}M" if n_params >= 1e6 else f"{n_params/1e3:.0f}K"
REPO_NAME = f"ThinkSpark-{tag}"                       # e.g. ThinkSpark-4.4M
REPO_ID = f"{HF_USER}/{REPO_NAME}"

meta = json.loads((CKPT / "meta.json").read_text())
labels = json.loads((CKPT / "label_maps.json").read_text())
intents = labels.get("intents", [])
langs = labels.get("lang_list", [])
tm_path = Path("artifacts/thinkspark/test_metrics.json")
tm = json.loads(tm_path.read_text()) if tm_path.exists() else {}


def m(k, d="—"):
    v = tm.get(k)
    return f"{v:.3f}" if isinstance(v, (int, float)) else d


# ---- 2. model card ---------------------------------------------------------
iso = [l for l in langs if l != "hi_en"]             # hi_en isn't a valid ISO tag
frontmatter = (
    "---\n"
    "license: apache-2.0\n"
    "library_name: pytorch\n"
    "pipeline_tag: text-classification\n"
    "tags:\n  - backchannel\n  - filler-words\n  - voice-agent\n  - multilingual\n"
    "  - thinking-sound\n  - low-latency\n"
    "language:\n" + "".join(f"  - {c}\n" for c in iso) +
    "---\n\n"
)
card = frontmatter + f"""# {REPO_NAME} — multilingual "thinking-sound" predictor

**{n_params:,} parameters (~{tag}).** A tiny byte-level dual-encoder that predicts the
human *backchannel / thinking sound* a voice agent should murmur in the gap between
the user's speech (STT) and the agent's reply (TTS) — `hmm`, `अच्छा`, `એક સેકન્ડ`,
`ええと` — in the right **language, native script, register and emotion**. CPU-friendly,
single-digit-ms inference.

## What it predicts
Given the user's current utterance (**input**, primary) + the **past conversation**
(context, any language/mix), it outputs:
- **language** ({len(langs)}): {", ".join(langs)}
- **intent** — {len(intents)} agent super-reactions: {", ".join(intents)}
- **register**, **emotion**, **filler_type** (`sound / word / sound_word / words / none`)

A curated filler dictionary then samples the actual spoken spark for
`(language, intent, filler_type)`.

## Test metrics
| metric | value |
|---|---|
| intent acc / top-2 / macro-F1 | {m('acc_intent')} / {m('top2_intent')} / {m('macro_f1_intent')} |
| language acc | {m('acc_language')} |
| emotion / filler_type acc | {m('acc_emotion')} / {m('acc_filler_type')} |

## Usage
```python
from huggingface_hub import snapshot_download
from thinkspark.infer import ThinkSparkPredictor

local = snapshot_download("{REPO_ID}")
pred = ThinkSparkPredictor(local, f"{{local}}/filler_dictionary.json")

pred.predict(
    input_text="अरे यार फिर से वही दिक्कत",
    context="User: रिफंड नहीं आया\\nAgent: sir I am checking\\nUser: कितनी बार बोलूँ",
)
# -> {{'spark': 'माफ़ कीजिए', 'intent': 'soothe', 'language': 'hi', ...}}
```

## Architecture
Byte-level tokenizer (zero-OOV across every script) -> separate input & context
encoders -> the input **cross-attends into** the context (input is primary, context
modulates) -> 5 heads. Trained with focal loss + class-balancing; native-script
language is pinned by a script guard at inference.

*Generated by kupe-thinkspark; data via Sarvam. Native-speaker QA recommended for
urban/code-mixed and low-resource fillers.*
"""
Path("README.md").write_text(card, encoding="utf-8")

# ---- 3. create repo + upload ----------------------------------------------
api = HfApi(token=HF_TOKEN)
api.create_repo(REPO_ID, repo_type="model", exist_ok=True, private=False)

api.upload_file(path_or_fileobj="README.md", path_in_repo="README.md", repo_id=REPO_ID)
api.upload_file(path_or_fileobj=str(CKPT / "model.pt"), path_in_repo="model.pt", repo_id=REPO_ID)
api.upload_file(path_or_fileobj=str(CKPT / "meta.json"), path_in_repo="meta.json", repo_id=REPO_ID)
api.upload_file(path_or_fileobj=str(CKPT / "label_maps.json"), path_in_repo="label_maps.json", repo_id=REPO_ID)
api.upload_file(path_or_fileobj=str(FILLER), path_in_repo="filler_dictionary.json", repo_id=REPO_ID)

# ONNX artifacts for the CPU voice worker (kupe-agents downloads these at warmup).
# Produce them first with: python scripts/export_onnx.py --ckpt artifacts/thinkspark/best
ONNX_DIR = Path("artifacts/onnx")
if (ONNX_DIR / "thinkspark.onnx").exists():
    api.upload_file(path_or_fileobj=str(ONNX_DIR / "thinkspark.onnx"),
                    path_in_repo="thinkspark.onnx", repo_id=REPO_ID)
    api.upload_file(path_or_fileobj=str(ONNX_DIR / "onnx_meta.json"),
                    path_in_repo="onnx_meta.json", repo_id=REPO_ID)
    print("   + onnx: thinkspark.onnx, onnx_meta.json")
else:
    print("   (no artifacts/onnx/thinkspark.onnx — run scripts/export_onnx.py to include ONNX)")

# ship the inference code so `from thinkspark.infer import ThinkSparkPredictor` just works
api.upload_folder(folder_path="thinkspark", path_in_repo="thinkspark", repo_id=REPO_ID,
                  ignore_patterns=["__pycache__/*", "*.pyc"])
api.upload_folder(folder_path="config", path_in_repo="config", repo_id=REPO_ID,
                  ignore_patterns=["__pycache__/*", "*.pyc"])

print(f"✅ pushed -> https://huggingface.co/{REPO_ID}   ({n_params:,} params, {tag})")
# Adjust CKPT / FILLER paths if your working dir differs
# (e.g. /kaggle/working/kupe-thinkspark/...).
